# Generated by Django 4.2.3 on 2023-10-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='active',
        ),
    ]
