# Generated by Django 4.2.3 on 2023-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_remove_variation_image_alter_variation_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='size',
            field=models.CharField(max_length=200),
        ),
    ]
