# Generated by Django 4.2.3 on 2023-10-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_product_price_product_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
