# Generated by Django 4.2.3 on 2023-10-17 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_remove_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
