# Generated by Django 4.2.3 on 2023-10-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
