# Generated by Django 4.2.3 on 2023-10-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_remove_variation_deleted_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
