# Generated by Django 4.2.3 on 2023-11-14 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_category_category_offer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='product_variation',
        ),
        migrations.RemoveField(
            model_name='userrating',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
