# Generated by Django 4.2.3 on 2023-11-15 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0054_sales'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='referral_offer',
            new_name='offer',
        ),
    ]
