# Generated by Django 4.2.3 on 2023-11-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_rename_referral_offer_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer',
        ),
        migrations.AddField(
            model_name='product',
            name='product_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=100, null=True),
        ),
    ]
