# Generated by Django 4.2.3 on 2023-11-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0059_contact_email_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
    ]
