# Generated by Django 4.2.5 on 2023-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0063_remove_address_is_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_offer',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
