# Generated by Django 4.2.3 on 2023-11-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0064_alter_product_product_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='final_price',
        ),
    ]
